### ISSUE TITLE
Syntax error in cpanfile

### ISSUE THREAD

**Issue by despean** [mrueda/beacon2-tools#4]
```
--> Working on .
Configuring /home/ubuntu/Beacon2-main ... FAIL
! Parsing cpanfile failed: syntax error at cpanfile line 7, near "'Term::ANSIColor'          # To provide colors to STDOU
requires "
! Configuring . failed. See /home/ubuntu/.cpanm/work/1655928952.2169/build.log for details.
```
Notice the cpanfile was missing semi colons. Added those local and everything was fine

**Comment by mrueda** [comment]
Thanks @despean for catching this. Please note that we'll be introducing a few more changes soon (e.g., repo name change) to accommodate referee's comments on the technical paper submitted to Bioinformatics.
